env:
  - GO111MODULE=on
before:
  hooks:
    - mkdir -p /home/runner/go/pkg/mod/github.com
    - chmod 755 /home/runner/go/pkg/mod/github.com
    - git clone --depth=1 -b dev https://github.com/FloatTech/gocq.git /home/runner/go/pkg/mod/github.com/!mrs4s/go-cqhttp@v1.0.0-beta8-fix2
    - git clone --depth=1 https://github.com/FloatTech/ZeroBot.git /home/runner/go/pkg/mod/github.com/wdvxdr1123/!zero!bot@v1.4.2-0.20220207114459-068919ac2b02
    - go mod tidy -compat=1.17
builds:
  - id: nowin
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
  - id: win
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - windows
    goarch:
      - 386
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w

checksum:
  name_template: "gocqzbp_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - fix typo
      - Merge pull request
      - Merge branch
      - Merge remote-tracking
      - go mod tidy

archives:
  - id: nowin
    builds:
      - nowin
      - win
    name_template: "gocqzbp_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - license: AGPL 3.0
    homepage: https://github.com/FloatTech/gocqzbp
    file_name_template: "gocqzbp_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats:
      - deb
      - rpm
    maintainer: FloatTech
